### PR TITLE
[test] Add warm reset tests to ROM integration test suite

### LINKED ISSUE #1032: ROM test: Validate fix for #817: warm reset during hitless update
See #817

Test should warm-reset caliptra part-way through a hitless update, and make sure it fails with the expected error code.

### LINKED ISSUE #1033: ROM test: Validate fix for #628: warm reset during cold reset
See #628

Test should warm-reset caliptra part-way through a cold boot, and make sure it fails with the expected error code.

### PR DESCRIPTION
**Pull request by mhatrevi**

### CODE REVIEW

File: rom/dev/tests/rom_integration_tests/test_warm_reset.rs [hunk 1]
```diff
@@ -0,0 +1,236 @@
...
+        ..Default::default()
+    };
+
+    let (mut hw, image_bundle) =
+        helpers::build_hw_model_and_image_bundle(fuses, ImageOptions::default());
+
+    // Manually put the firmware in the mailbox because
+    // HwModel::upload_firmware returns only when the transaction is complete.
+    // This is too late for this test.
+    let buf: &[u8] = &image_bundle.to_bytes().unwrap();
```
Comment (korran) [inline rom/dev/tests/rom_integration_tests/test_warm_reset.rs:122]: Would hw.start_mailbox_execute(FW_LOAD_CMD_OPCODE, ...) work?

Comment (korran) [reply rom/dev/tests/rom_integration_tests/test_warm_reset.rs:122]: That places the command in the mailbox but doesn't wait for it to complete.l

**Review by korran — DISMISSED** [review]

File: rom/dev/tests/rom_integration_tests/test_warm_reset.rs (hunk 1 above)
Comment (mhatrevi) [reply rom/dev/tests/rom_integration_tests/test_warm_reset.rs]: Updated.

**Review by korran — APPROVED** [review]
