### PR TITLE
[fix] Add CFI checks to svn_check_required in verifier library

### LINKED ISSUE #910: Critical Functions Not CFI Protected
Finding NCC-MSFT283-BKC

Gaps in Caliptra’s CFI implementation may enable bypassing of anti-rollback protection.

Add CFI protection to two functions: svn_check_required and anti_rollback_disable in caliptra-sw/image/verify/src/verifier.rs

### PR DESCRIPTION
**Pull request by mhatrevi**
Addresses Issue: https://github.com/chipsalliance/caliptra-sw/issues/910

CFI check confirmation:
000002c8 <caliptra_image_verify::verifier::ImageVerifier<Env>::svn_check_required::h0ebe396502ecf1b7>:
     2c8: 41 11        	c.addi	sp, -16
     2ca: 06 c6        	c.swsp	ra, 12(sp)
     2cc: 37 05 03 30  	lui	a0, 196656
     2d0: 6c 41        	c.lw	a1, 68(a0)
     2d2: 8d 89        	c.andi	a1, 3
     2d4: 2e c2        	c.swsp	a1, 4(sp)
     2d6: 4c 00        	c.addi4spn	a1, sp, 4
     2d8: 92 45        	c.lwsp	a1, 4(sp)
     2da: 99 c9        	c.beqz	a1, 0x2f0 <.LBB4_2>
     2dc: 83 25 85 2c  	lw	a1, 712(a0)
     2e0: 85 89        	c.andi	a1, 1
     2e2: a3 05 b1 00  	sb	a1, 11(sp)
     2e6: 93 05 b1 00  	addi	a1, sp, 11
     2ea: 83 45 b1 00  	lbu	a1, 11(sp)
     2ee: 91 cd        	c.beqz	a1, 0x30a <.LBB4_6>

000002f0 <.LBB4_2>:
     2f0: 68 41        	c.lw	a0, 68(a0)
     2f2: 0d 89        	c.andi	a0, 3
     2f4: 19 c5        	c.beqz	a0, 0x302 <.LBB4_4>
     2f6: 37 05 03 30  	lui	a0, 196656
     2fa: 03 25 85 2c  	lw	a0, 712(a0)
     2fe: 05 89        	c.andi	a0, 1
     300: 11 a0        	c.j	0x304 <.LBB4_5>

00000302 <.LBB4_4>:
     302: 05 45        	c.li	a0, 1

00000304 <.LBB4_5>:
     304: bd 3f        	c.jal	0x282 <caliptra_cfi_lib::cfi::cfi_assert_eq::he67f64a571fd9c89>
     306: 01 45        	c.li	a0, 0
     308: 11 a0        	c.j	0x30c <.LBB4_7>

### CODE REVIEW

**Review by ericeilertson — DISMISSED** [review]

File: image/verify/src/verifier.rs [hunk 1]
```diff
@@ -586,7 +587,17 @@ impl<Env: ImageVerificationEnv> ImageVerifier<Env> {
     // Check if SVN check is required
     fn svn_check_required(&mut self) -> bool {
         // If device is unprovisioned or if anti-rollback is disabled, don't check the SVN.
-        !(self.env.dev_lifecycle() == Lifecycle::Unprovisioned || self.env.anti_rollback_disable())
+        if cfi_launder(self.env.dev_lifecycle()) == Lifecycle::Unprovisioned
+            || cfi_launder(self.env.anti_rollback_disable())
+        {
```
Comment (korran) [inline image/verify/src/verifier.rs:592]: Should we add some non-deterministic delay here?

File: image/verify/src/verifier.rs [hunk 2]
```diff
@@ -586,7 +587,17 @@ impl<Env: ImageVerificationEnv> ImageVerifier<Env> {
     // Check if SVN check is required
     fn svn_check_required(&mut self) -> bool {
```
Comment (korran) [inline image/verify/src/verifier.rs:588]: always(inline) to ensure that the cfi checks below are included in every check? Otherwise the code that checks the return value of this function is vulnerable to glitching...

**Review by korran — CHANGES_REQUESTED** [review]
We probably also need CFI protection for the SVN check itself (verify_info.svn < self.env.fmc_fuse_svn()?)

File: image/verify/src/verifier.rs (hunk 2 above)
Comment (mhatrevi) [reply image/verify/src/verifier.rs:588]: Updated

File: image/verify/src/verifier.rs (hunk 1 above)
Comment (mhatrevi) [reply image/verify/src/verifier.rs:592]: We have multiple CFI delays explicitly added before starting firmware validation; not too inclined on adding a delay here.

Comment (korran) [reply image/verify/src/verifier.rs:593]: This can be addressed in another PR, but I think in general we want to the CFI double checks throughout the code-base to be done much later in time than the original check.

**Review by korran — APPROVED** [review]

**Review by jhand2 — APPROVED** [review]
