### PR TITLE
[fix] Overflow checks for image verifier

### LINKED ISSUE #580: Findings from fuzzing image/verify
Fuzzing image/verify with https://github.com/chipsalliance/caliptra-sw/pull/577 - specifically, libFuzzer - panics with the following:
`thread '<unnamed>' panicked at 'attempt to subtract with overflow', <caliptra-sw>/image/verify/src/verifier.rs:525:33`

### PR DESCRIPTION
**Pull request by mhatrevi**
This fix addresses https://github.com/chipsalliance/caliptra-sw/issues/580

### CODE REVIEW

File: image/types/src/lib.rs [hunk 1]
```diff
@@ -406,8 +407,13 @@ pub struct ImageTocEntry {
 }
 
 impl ImageTocEntry {
-    pub fn image_range(&self) -> Range<u32> {
-        self.offset..self.offset + self.size
+    pub fn image_range(&self) -> CaliptraResult<Range<u32>> {
+        let (end, overflow) = self.offset.overflowing_add(self.size);
```
Comment (korran) [inline image/types/src/lib.rs:411]: Consider writing this as:

```
        let err = CaliptraError::IMAGE_VERIFIER_ERR_TOC_ENTRY_RANGE_ARITHMETIC_OVERFLOW;
        let end_offset = self.offset.checked_add(self.size).ok_or(err)?;
        Ok(self.offset..end_offset)
```

**Review by korran — APPROVED** [review]
