### PR TITLE
Test failed DPE command populates mbox header with correct error code

### LINKED ISSUE #1121: [RT Test] Test failed DPE command populates mbox header with correct error code

### PR DESCRIPTION
**Pull request by sree-revoori1**
Fixes #1121

### CODE REVIEW

File: runtime/tests/runtime_integration_tests/common.rs [hunk 1]
```diff
@@ -172,7 +184,12 @@ pub fn execute_dpe_cmd(model: &mut DefaultHwModel, dpe_cmd: &mut Command) -> Res
         &resp[core::mem::size_of_val(&resp_hdr.hdr.chksum)..],
     ));
 
-    parse_dpe_response(dpe_cmd, &resp_hdr.data[..resp_hdr.data_size as usize])
+    let resp_bytes = &resp_hdr.data[..resp_hdr.data_size as usize];
+    Some(match expected_result {
+        DpeResult::Success => parse_dpe_response(dpe_cmd, resp_bytes),
+        DpeResult::DpeCmdFailure => Response::Error(ResponseHdr::read_from(resp_bytes).unwrap()),
+        DpeResult::MboxCmdFailure(_) => panic!("Not possible"),
```
Comment (jhand2) [inline runtime/tests/runtime_integration_tests/common.rs:191]: nit: You can use the `unreachable!` macro and then have a short message explaining why.

**Review by jhand2 — DISMISSED** [review]

File: runtime/tests/runtime_integration_tests/common.rs (hunk 1 above)
Comment (sree-revoori1) [reply runtime/tests/runtime_integration_tests/common.rs]: Done

**Review by jhand2 — APPROVED** [review]
