### PR TITLE
nightly: Add regression test against 2.0.0 ROM

### LINKED ISSUE #3110: Start regression tests against 2.0.0 ROM with current FW/emulator/etc.

### PR DESCRIPTION
**Pull request by swenson**
We add the frozen 2.0.0 ROM.

We also fix a flaky invoke_dpe test.

Fixes #3110

Also includes a cherry pick:

Reduce CSR stress iteration count (#2977)

This takes a long time on the subsystem FPGA.

2.0 Nightly tests passed on this code: https://github.com/chipsalliance/caliptra-sw/actions/runs/21729198533

(cherry picked from commit 5dd8a99aff6d9f4dc9b63a9cce04de1ae837664e)

### CODE REVIEW

File: rom/dev/tests/rom_integration_tests/test_idevid_derivation.rs [hunk 1]
```diff
@@ -108,12 +108,15 @@ fn fuses_with_random_uds() -> Fuses {
 
 #[test]
 fn test_generate_csr_envelop_stress() {
+    if true {
+        return; // ignore for now so we can debug other tests
+    }
```
Comment (zhalvorsen) [inline rom/dev/tests/rom_integration_tests/test_idevid_derivation.rs]: Do you still plan to ignore this test? Can we do it through the nextest filter?

Comment (swenson) [reply rom/dev/tests/rom_integration_tests/test_idevid_derivation.rs]: Oh oops. Left this in! Let me remove this. :)

**Review by zhalvorsen — APPROVED** [review]

**Comment by swenson** [comment]
Thanks!
