### PR TITLE
[fix] Execute SHA2-256 KAT before executing the ROM integrity check

### LINKED ISSUE #1312: FIPS Requirement - ROM Must Perform SHA KAT before ROM Integrity Uses SHA Engine
The ROM must fulfill the FIPS requirement AS10.20:

A cryptographic algorithm that is used to perform the approved integrity technique for the pre-operational software/firmware test shall [10.20] first pass the cryptographic algorithm self-test specified in 7.10.3.2.

The ROM must perform the SHA KAT if using the SHA HW to perform the ROM integrity check.

### PR DESCRIPTION
**Pull request by mhatrevi**
This change re-arranges the KAT and ROM integrity check execution such that the SHA2-256 KAT is run before running the ROM integrity check. This is needed per FIPS requirement AS10.20.

### CODE REVIEW

**Review by FerralCoder — DISMISSED** [review]

**Review by korran — DISMISSED** [review]

**Comment by mhatrevi** [comment]
@JohnTraverAmd Can you review this?

File: rom/dev/src/main.rs [hunk 1]
```diff
@@ -184,9 +185,38 @@ pub extern "C" fn rom_entry() -> ! {
...
+    Sha384Kat::default().execute(env.sha384)?;
+
+    cprintln!("[kat] SHA2-384-ACC");
+    Sha384AccKat::default().execute(env.sha384_acc, env.sha_acc_lock_state)?;
+
+    cprintln!("[kat] ECC-384");
+    Ecc384Kat::default().execute(env.ecc384, env.trng)?;
+
+    cprintln!("[kat] HMAC-384");
+    Hmac384Kat::default().execute(env.hmac384, env.trng)?;
```
Comment (mhatrevi) [inline rom/dev/src/main.rs:211]: Rename this to Hmac384KdfKat.

**Review by FerralCoder — DISMISSED** [review]

File: rom/dev/src/main.rs [hunk 2]
```diff
@@ -184,9 +185,22 @@ pub extern "C" fn rom_entry() -> ! {
 }
 
 fn run_fips_tests(env: &mut KatsEnv) -> CaliptraResult<()> {
+    cprintln!("[kat] ++");
```
Comment (korran) [inline rom/dev/src/main.rs:188]: This is repeating that what's done at the top of kat::execute_kat(). Do we care?

**Review by JohnTraverAmd — DISMISSED** [review]

**Review by korran — DISMISSED** [review]

**Review by korran — APPROVED** [review]
