### PR TITLE
[fix] Add Caliptra version to all certificate common names

### LINKED ISSUE #974: Add Caliptra version to all certificate common names
e.g., "Caliptra 1.0 LDevID"

This enables class-wide revocation should we find an issue in Caliptra 1.0.

### PR DESCRIPTION
**Pull request by mhatrevi**
This fix addresses issue# https://github.com/chipsalliance/caliptra-sw/issues/974

### CODE REVIEW

**Review by varuns-nvidia — DISMISSED** [review]

File: x509/build/build.rs [hunk 1]
```diff
@@ -106,6 +106,6 @@ fn gen_rt_alias_cert(out_dir: &str) {
                 digest: &[0xCD; 48],
             },
         }]);
-    let template = bldr.tbs_template("Caliptra Rt Alias", "Caliptra FMC Alias");
+    let template = bldr.tbs_template("Caliptra 1.0 Rt Alias", "Caliptra 1.0 FMC Alias");
```
Comment (jhand2) [inline x509/build/build.rs:109]: You'll also need to update this to match: https://github.com/chipsalliance/caliptra-sw/blob/main/runtime/src/dpe_platform.rs#L80

Comment (mhatrevi) [reply x509/build/build.rs:109]: Fixed.

**Review by jhand2 — DISMISSED** [review]

**Review by jhand2 — APPROVED** [review]

**Review by korran — APPROVED** [review]

**Review by bluegate010 — APPROVED** [review]
